steps:
  # Step 1: CPU step that starts GPU agent
  - label: "Start GPU"
    key: "gpu-starter"
    command: modal_client.sh

  # Step 2: The actual GPU work, which will be picked up by our Modal GPU agent
  - label: "Do GPU Work" 
    key: "gpu-work"
    command: nvidia-smi
    agents:
      job: "$$BUILDKITE_BUILD_NUMBER_gpu"  # Match the job-id we gave to Modal