steps:
  # Step 1: CPU step that starts GPU agent
  - label: "Modal Client"
    key: "gpu-launcher"
    command: |
      pip install -U modal
    
      # Create modal config file using secrets
      cat << EOF > ~/.modal.toml
      [default]
      token_id = "$(buildkite-agent secret get modal_token_id)"
      token_secret = "$(buildkite-agent secret get modal_token_secret)"
      EOF

      # Now run modal
      modal run main.py --queue A100

  # Step 2: The actual GPU work, which will be picked up by our Modal GPU agent
  - label: "Modal GPU Agent" 
    key: "gpu-agent"
    agents:
      queue: "A100"
    command: 
    - bash .buildkite/nightly-benchmarks/scripts/run-performance-benchmarks.sh