steps:
  - label: "A100"
    key: "gpu-runner"
    env:
      GPU: "a100"
      VLLM_USAGE_SOURCE: "ci-test"
    commands:
      - pip install -U modal
      - |
        # Create modal config file using secrets
        cat << EOF > ~/.modal.toml
        [default]
        token_id = "$(buildkite-agent secret get modal_token_id)"
        token_secret = "$(buildkite-agent secret get modal_token_secret)"
        EOF
      - export HF_TOKEN="$(buildkite-agent secret get hf_token_secret)"
      - modal run -q runner --command "bash ./.buildkite/nightly-benchmarks/scripts/run-performance-benchmarks.sh"