steps:
  - command: |
      # Generate unique ID for this pipeline run
      JOB_ID="gpu-job-${BUILDKITE_BUILD_NUMBER}-${RANDOM}"
      
      # Start the Modal GPU agent and wait (this blocks until GPU job completes)
      modal run main.py --job-id=$JOB_ID &
      MODAL_PID=$!
      
      # Give the GPU agent time to start up
      sleep 10
      
      # Upload the GPU job step
      cat << EOF | buildkite-agent pipeline upload
      steps:
        - label: "GPU Job"
          key: "gpu-task"
          command: "echo 'Running on GPU' && sleep 30"  # Replace with your actual GPU command
          agents:
            job: $JOB_ID
      EOF
      
      # Wait for Modal to finish (which will happen after GPU job completes)
      wait $MODAL_PID