steps:
  # Step 1: CPU step that starts GPU agent
  - label: "Modal Client"
    key: "gpu-launcher"
    env:
      GPU: "a100"
      BUILDKITE_COMMIT: "$BUILDKITE_COMMIT"
      VLLM_USAGE_SOURCE: "ci-test"
      HF_TOKEN:
        from-secret-key:
          name: hf-token-secret
          key: token
    commands:
      - pip install -U modal
      - |
        # Create modal config file using secrets
        cat << EOF > ~/.modal.toml
        [default]
        token_id = "$(buildkite-agent secret get modal_token_id)"
        token_secret = "$(buildkite-agent secret get modal_token_secret)"
        EOF
      - modal run main.py
